import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const BASE_URL = 'https://vaonix-shop.fr';
const SITEMAP_PATH = path.join(__dirname, '../public/sitemap.xml');
const PRODUCTS_JSON_PATH = path.join(__dirname, '../src/config/products.example.json');
const MASTER_CSV_PATH = path.join(__dirname, '../products_master.csv');

// Static routes
const staticRoutes = [
    '/',
    '/produits',
    '/produits/liste',
    '/panier',
    '/a-propos',
    '/ressources',
    '/blog',
    '/contact',
    '/mentions-legales',
    '/cgv',
    '/livraison-retours'
];

async function generateSitemap() {
    try {
        let sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
`;

        // Add static routes
        staticRoutes.forEach(route => {
            sitemap += `  <url>
    <loc>${BASE_URL}${route}</loc>
    <changefreq>weekly</changefreq>
    <priority>${route === '/' ? '1.0' : '0.8'}</priority>
  </url>
`;
        });

        // Strategy: Try CSV first (full data), then JSON (fallback)
        if (fs.existsSync(MASTER_CSV_PATH)) {
            console.log(`Reading products from: ${MASTER_CSV_PATH}`);
            const fileContent = fs.readFileSync(MASTER_CSV_PATH, 'utf8');
            const lines = fileContent.split(/\r?\n/);

            if (lines.length > 0) {
                const headers = lines[0].split(',');
                const handleIndex = headers.indexOf('Handle');

                if (handleIndex !== -1) {
                    const uniqueHandles = new Set();

                    for (let i = 1; i < lines.length; i++) {
                        const line = lines[i];
                        if (!line.trim()) continue;

                        // Simple split is okay for Handle if it's the first column or doesn't have commas
                        // But handles shouldn't have commas anyway. 
                        // Be careful about quoted fields before it.
                        // Assuming standard CSV where simple split might fail if earlier cols have commas.
                        // Let's use a regex to find the handle if simple split is risky?
                        // Actually, products_master.csv generated by our script puts Handle at index 0 !
                        // Let's verify that assumption.

                        const parts = line.split(',');
                        // If Handle is index 0, this is safe.

                        let handle = parts[handleIndex];
                        // Cleanup quotes if any
                        if (handle && handle.startsWith('"') && handle.endsWith('"')) {
                            handle = handle.slice(1, -1);
                        }

                        if (handle && !uniqueHandles.has(handle)) {
                            uniqueHandles.add(handle);
                            sitemap += `  <url>
    <loc>${BASE_URL}/produit/${handle}</loc>
    <changefreq>daily</changefreq>
    <priority>0.9</priority>
  </url>
`;
                        }
                    }
                    console.log(`Added ${uniqueHandles.size} products to sitemap from CSV.`);
                } else {
                    console.warn('Handle column not found in CSV headers');
                }
            }
        } else if (fs.existsSync(PRODUCTS_JSON_PATH)) {
            console.log('CSV not found, falling back to JSON example data.');
            const productsData = JSON.parse(fs.readFileSync(PRODUCTS_JSON_PATH, 'utf8'));

            if (productsData.products && Array.isArray(productsData.products)) {
                productsData.products.forEach(product => {
                    if (product.handle) {
                        sitemap += `  <url>
    <loc>${BASE_URL}/produit/${product.handle}</loc>
    <changefreq>daily</changefreq>
    <priority>0.9</priority>
  </url>
`;
                    }
                });
                console.log(`Added ${productsData.products.length} products to sitemap from JSON.`);
            }
        } else {
            console.warn('No product data source found (checked CSV and JSON).');
        }

        sitemap += '</urlset>';

        fs.writeFileSync(SITEMAP_PATH, sitemap);
        console.log(`Sitemap generated successfully at ${SITEMAP_PATH}`);

    } catch (error) {
        console.error('Error generating sitemap:', error);
    }
}

generateSitemap();
